# Generated by Django 5.0.2 on 2024-02-22 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendancedate', models.DateField()),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('description', models.TextField()),
                ('employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.employees')),
            ],
        ),
    ]
